lib/mox.ex, test/mox_test.exs
Resolves #2 
`stub/3` allows a stub to be defined without being subject to the verification rules that expectations are.  
```
stub(CalcMock, :add, fn(x, y) -> x + y end)
assert CalcMock.add(1, 1) == 2
```
- This implementation only allows one stub per function/arity so subsequent calls to `stub/3` will overwrite the setup of any previous.  
- If expectations exist for the same function/arity then those will take precedence when invocations occur.  
- Once all expectations are met, invocations will use the function provided to `stub/3` if available.
-   The stub can be called zero or as many times as you want.
=> Implementing stub/3

lib/mox.ex, lib/mox/application.ex, lib/mox/server.ex
This is first step into https://github.com/plataformatec/mox/issues/5
As advised by @josevalim , I have replaced the Registry with custom GenServer implementation, keeping all the existing functionality intact.
=> Replace Registry with GenServer

lib/mox.ex, lib/mox/server.ex, test/mox_test.exs
This is another step en route towards https://github.com/plataformatec/mox/issues/5
After this pull request is merged, one can share expectations and stubs with other than current testing processes using:
allow(MyMock, pid)
When we dispatch calls, we first check if caller is owner or been granted access, and fetch appropriate function accordingly.
=> Allow other processes to share mocks defined by current process

lib/mox.ex
A user of the library (yay) found a bug here: https://elixirforum.com/t/compilation-order-during-tests/9459
@ericmj quickly found a solution (<3) which is incorporated to this PR.
=> Use Code.ensure_compiled? vs Code.ensure_loaded? to ensure the module is available

.formatter.exs, lib/mox.ex, lib/mox/server.ex, mix.exs, test/mox_test.exs
So yeah, I made a few circles with this back and forth. My quick'n'dirty initial implementation was quite similar to this one, then decided we need 2 separate servers for global and private modes, but in the end I did like the original version more. Just made some tweaks to it.
So the general idea is that we have 2 modes (so far): private and global.
In private mode the only process who can declare expectations, stubs, and also consume them and verify is the same process. In private mode tests can run in async mode.
In global mode tests no longer can run in async mode. The same process which declares expectations, needs to verify them, but any process can consume them.
Private is the default mode. You can switch to global mode with `set_mox_global!` in your `setup` block.
You can also set …
=> Add :global mode

README.md
Updates `def deps` example to use the latest minor version of Mox.
=> Update mox version in README install instructions

lib/mox.ex, test/mox_test.exs
Fixes https://github.com/plataformatec/mox/issues/26
This is **super** rough and needs to be cleaned up.
I wanted to ask if we should support a single behaviour (not in a list), for example:
`Mox.defmock(MyMock, for: Calculator)`
or
`Mox.defmock(MyMock, for: [Calculator])`
I'm leading towards supporting both. Thoughts?
=> Support mocking multiple behaviours

lib/mox.ex, test/mox_test.exs
When using Mox it can be hard, once we're using a mock in the test environment, to replace the mock with the "real" implementation in order to do any type of integration testing. For example, say we have an umbrella app with a `storage` app and a `web` app. `web` provides a web interface and communicates to `storage` via a defined behaviour to access the data layer. In order to unit test `web` we use Mox to replace `Storage` with `MockStorage`. But we also want to have a few integration tests that verify the integration of these two apps. The problem is that once `MockStorage` is in place we can't switch back to `Storage`. We need a way to stub `MockStorage` and tell it "act just like the real `Storage` in this test", without having to explicitly stub every function in the behaviour like …
=> Adds stub_with function for stubbing a mock with module.

lib/mox.ex, test/mox_test.exs
Change guard clause for `expect/4` to verify that `n>=0`. This allows `expect` to explicitly assert that a function was not called. Addresses #32.
=> Allow expect/4 to assert function not called

README.md
Both take you to the hex.pm page for Mox, which I think is useful.
=> Add downloads and version hex.pm badges

lib/mox.ex, test/mox_test.exs
Mox currently does not support explicit allowances with registered names; it only supports explicit allowances via `pid`s.  Attempting to create an allowance for a process using a registered name throws a `FunctionClauseError`. This PR adds a function clause for `allow/3` that accepts locally registered names (atoms) or registry tuples.
[Related Issue #43](https://github.com/plataformatec/mox/issues/43)
=> Support registered process names for allowances

lib/mox.ex, test/mox_test.exs
This can be useful if you create a shim to assist in testing. Now you can use your shim all of the time without having to know if Mox is in global mode or not.
Fixes #46
=> Creating an allowance in global mode is now ignored

.travis.yml, CHANGELOG.md, lib/mox.ex, lib/mox/server.ex, test/mox_test.exs, test/test_helper.exs
My first implementation passed the result of `Process.get(:"$callers")` in to the server for processing but it felt cleaner to do that call in `Mox` itself.
Questions:
* How should we stop the new tests from running when Elixir < 1.8?
* We could do feature detection by spawning a task and checking if it has `$callers` set?
* I didn't like this initially but I'm coming around to it. We could even use the same function in `assert_default_raise/2`
* Use an exunit tag and exclude it on some runs?
* Direct version detection with `System.version/0`
* Should we add a test that uses spawn directly and assert that that still fails?
* Is `$callers` documented anywhere besides the Elixir 1.8 release notes?
=> Use $callers to use expectations made in the calling process

mix.lock
Upgrade ex_doc to the latest version to get version switching and improved search functionality.
=> Upgrade ex_doc and earmark to latest versions

CHANGELOG.md, lib/mox.ex, test/mox_test.exs
This is useful if you have code that checks if a given function is implemented and only calls it in that case (or has completely separate behavior in the not-implemented case). By default all optional callbacks are implemented as functions.
Note: in the tests I didn't name all the defined mocks `MyMock` because I received warnings like:
warning: redefining module MyMock (current version defined in memory)
lib/mox.ex:316
Fixes #61
=> :skip_optional_callbacks option to `defmock` skips optional callbacks

lib/mox.ex
Thanks for mox and all your other work as usual :green_heart: :pray: :tada: 
I think it's most useful for when we can't pass the mock to the
system under test directly/we have to configure it in the test
environment. Hence I added it right underneath that section.
Not sure if that's the best choice or if a separate section
would be better. Happy for feedback!
Follow up to #76
=> Highlight the utility of stub_with/2

lib/mox.ex
See #41 - I wrote the docs based on my understanding of the other
docs, which turns out was wrong which I realized when finally
implementing it. Sorry.
I'll open another issue to ask about feature/acceptance tests then :)
=> stub_with/2 needs to be called in the process that uses it

lib/mox.ex, test/mox_test.exs, test/support/mocks.ex
Checks if the mock actually exports the function before it defines the stub. Fixes #95
=> Make stub_with work with skip_optional_callbacks

lib/mox.ex
The docs said that `set_mox_from_context` would call `set_global_mode` if the test context includes `async: true` but it's actually the other way around.
Having `async: true` leads to `set_private_mode` being called.
I've also added a bit on which mode is default (`:private`).
=> docs: Fix docs on auto setting mode from context

lib/mox.ex
- MyApp.MockWeatherAPI's behaviour defines the return value interger().
- MyApp.HumanizedWeather.humdity -> hum"i"dity
=> Fix mock return value to fit its behaviour and typo of HumanizedWeather function

lib/mox.ex
I'm sorry last my PR #102  doesn't cover all sections. Because I read only [Example] (https://hexdocs.pm/mox/Mox.html#module-example) section. So it was inconsistent.
This PR fix it, fixed mock behaviour return type and typo of function name.
=> Fix document

lib/mox.ex
Went with ~S over escaping the `#` char so that plain-text still remains readable and copy-pastable.
=> use ~S to prevent interpolation

lib/mox.ex
In moduledoc of mox.ex, has an example about how to define a mock, but the second argument passed to [defmock](https://hexdocs.pm/mox/Mox.html#defmock/2) is not a behaviour
=> Fix mox moduledoc

README.md
Hi @josevalim!
Two things I wanted to bring up. I combined them because I think the last one
is just tangentially related to the first one.
1) I was working with someone the other week and they mentioned the docs could
have used more of a step-by-step flow rather than the current flow.
The current docs work for me, but I like to try to listen to "first impression"
feedback when I do get it. I really listen when it is folks new to the
community. So, I thought that a good place to add the step by step version
would be on the README and we could keep the moduledocs as they are as they are
helpful as well.
The second point is below, related to where I added the docs (in the README)
and also somewhat tangential because I'm asking about preferences not only for
this library, but for libraries …
=> Add basic usage

lib/mox.ex
The code example explaining usage of `stub_with/2` was not a  valid ExUnit.setup block because it would return an atom rather than `:ok | keyword | map`.
This PR alters the code example to return `:ok`.
=> Update mox.ex moduledoc on stub_with

lib/mox.ex, lib/mox/server.ex, test/cluster_test.exs
The current guidelines for best practices suggest shipping mocked module names in module attributes, which are compile-time values effectively hardcoded into the `.beam` file.  Thus there may be cases, (especially for integration tests) where a remote node might have to handle a request with no way of connecting back to the relevant mox expectations associated with the test.
This PR makes mox cluster aware, so another node connected in the cluster can access the same mox checkouts on the primary node.
Additional documentation has not been provided, happy to add documentation.  The one big warning is `:global` registry should be synced after connecting the node, but *before* ensuring Applications are running in the "peer" node, or else there may not be a deterministic selection of the …
=> Cluster testing

lib/mox.ex
The docs are still slightly suggesting that `stub_with` can be used just as `defmock` function in the `test_helper.exs` file, which is not true. https://github.com/dashbitco/mox/issues/122 was not enough to prevent devs from doing that mistake again.
Moreover, if a developer does it, the `stub_with` call in the test helper won't raise any error (even though it has no effect); only later on in the test files they will meet unhelpful errors like `no expectation defined for ...`, making the root cause hard to discover.
Let's help avoiding it.
=> docs: Stop suggest calling `stub_with` at compilation time

lib/mox.ex, lib/mox/server.ex, test/mox_test.exs
Sometimes, especially in less-unit and more-integration tests, the process to allow to use expectations in not yet started. In such a case, it would be great to have an ability for late-bound-allowances.
This PR provides an ad-hoc implementation of `{:promise, fn -> resolve_pid_lately() end)}` allowance, which does not have any implications until used, and attempts late binding right before dispatch. For instance, for named processes, it might look like `{:promise, fn -> GenServer.whereis(DeferredProcess) end}`.
This is not elegant, but it might be useful for many developers. Now I have to use global allowance with stubs for that.
=> Accept `(-> pid())` in `allow/3`

test/mox_test.exs, test/support/mocks.ex
Before this PR the tests of `verify/0` didn't assert that failures would be reported across multiple Mocks and tests for `verify/1` didn't assert that failures in other Mocks would be ignored.
=> Improve `verify/0` and `verify/1` test coverage

lib/mox.ex, test/mox_test.exs
Allow denying a call to a mock with clearer intentions.
Closes #145.
=> Add `Mox.deny/3`

lib/mox.ex
`:erlang.fun_info/1` calls `:erlang.fun_info/2` for each function information, since we need only the arity we can just get this information directly for a small performance improvement.
```
❯ mix profile.fprof -e ":erlang.fun_info(&Function.identity/1, :arity)"
...
CNT    ACC (ms)    OWN (ms)     
Total                                                                3       0.011       0.011     
:fprof.apply_start_stop/4                                            0       0.011       0.006     
anonymous fn/0 in :elixir_compiler_1.__FILE__/1                      1       0.005       0.004     
:erlang.fun_info/2                                                   1       0.001       0.001     
:undefined                                                           0       0.000       0.000 …
```
=> Use :erlang.fun_info/2 instead of :erlang.fun_info/1

lib/mox.ex
when reading stub_with documentation, I noticed that the behaviour name in the example was  wrong:
```
defmodule MyApp.WeatherAPI do
@callback temp(MyApp.LatLong.t()) :: {:ok, integer()}
@callback humidity(MyApp.LatLong.t()) :: {:ok, integer()}
end
defmodule MyApp.StubWeatherAPI do
@behaviour WeatherAPI
def temp(_loc), do: {:ok, 30}
def humidity(_loc), do: {:ok, 60}
end
```
so I added the missing part:
```
defmodule MyApp.StubWeatherAPI do
@behaviour MyApp.WeatherAPI
def temp(_loc), do: {:ok, 30}
def humidity(_loc), do: {:ok, 60}
end
```
=> fix stub_with/2 documentation

lib/mox.ex
Today `stub_with` calls `stub` for each functions that needs to be stubbed. This causes a significant overhead because some validations being done repeatedly, and sending multiple messages to store the state change. 
This PR updates `stub_with`  to avoid the issues above by storing a list with the stub key and expectation, and sending a single state update.
```
Name                   ips        average  deviation         median         99th %
bench (PR)         33.02 K       30.28 μs    ±25.30%       28.40 μs       65.52 μs
bench (main)        2.88 K      347.63 μs     ±9.18%      339.18 μs      453.12 μs
Comparison: 
bench (PR)         33.02 K
bench (main)        2.88 K - 11.48x slower +317.34 μs
Memory usage statistics:
Name                 average  deviation         median         99th …
```
=> Optimize stub_with

lib/mox.ex
Today Mox does a ownership check before doing an update to store the expectations. This call can be avoided because NimbleOwnership already does this same check on `get_and_update`, and the error allows us to do the error mapping.
```
Name                   ips        average  deviation         median         99th %
bench (PR)         36.47 K       27.42 μs    ±34.15%       25.69 μs       61.83 μs
bench (main)       32.33 K       30.93 μs    ±34.77%       28.91 μs       66.20 μs
Comparison: 
bench (PR)         36.47 K
bench (main)       32.33 K - 1.13x slower +3.52 μs
Memory usage statistics:
Name                 average  deviation         median         99th %
bench (PR)           7.08 KB     ±0.02%        7.08 KB        7.08 KB
bench (main)         7.53 KB     ±0.15%        7.53 KB …
```
=> Remove redundant ownership check

lib/mox.ex, test/mox_test.exs
@josevalim and I talked about this and I think this naive approach could already be enough, but I threw this together real quick just to open the discussion.
=> Use `process_info(PID, parent)`

lib/mox.ex
When testing a process that calls a mock inside its init/1, I ran into an Mox.UnexpectedCallError because the process wasn’t yet started when defining Mox.allow/3.
The fix was to use a deferred function with Mox.allow/3, so that Mox resolves the process later when the mock is actually invoked.
This change updates the docs to clarify that deferred functions can be used in such cases.
=> Clarify Mox.allow/3 usage with deferred functions
